name: app
description: A community built wallet for Zenon
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  znn_sdk_dart:
    path: ../znn_sdk_dart/

  hex: ^0.2.0
  bip39: ^1.0.6
  get: 4.3.8 # state management
  logger: ^1.1.0
  http: ^0.13.4
  desktop_window: ^0.4.0 #set desktop window size
  pull_to_refresh: 2.0.0
  shimmer: 2.0.0 # loading effect
  simple_animations: 4.0.1
  supercharged: 2.1.1
  flex_color_scheme: ^3.0.1 # themes
  app_settings: 4.1.1
  connectivity_plus: 2.0.2
  bubble_tab_indicator: 0.1.6
  path_provider: ^2.0.6
  file_picker: 4.2.1
  get_storage: 2.0.3 # persistence
  flutter_linkify: 5.0.2
  url_launcher: 6.0.12
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
